### ISSUE TITLE
Alternate ACME baseuri appears to fail when running API under context path

### ISSUE THREAD

**Issue by Magnus1990P** [ohadschn/letsencrypt-webapp-renewer#50] opened 2018-05-23 11:28 UTC
Hi.
It appears that the web job fails when changing the base URI to an alternative CA which is running under a context path and subdomain.  It works well with the CertBot client on standard linux-boxes, but fails to read the JSON string when using the following URI for access, https://api.buypass.com/acme/.

My guess is that the ACME sharp library which utilises the URL library, which can truncate when combining a baseuri with the additional query, eg. directory.
If the base URI contains a context path without a trailing /, it will remove the entire relative context path and just append its new relative path.

Eg. https://example.com/test/ will result in https://example.com/test/directory if combined with directory.
https://example.com/test will result in https://example.com/directory if combined with directory.

I have been unable to confirm this suspicion about somewhere in the code either the trailing slash is removed or it fails to identify the context path in the base URL. 

Below is a log for testing a FQDN against the https://api.buypass.com/acme/ base URI.
[https://api.buypass.com/acme/directory](https://api.buypass.com/acme/directory) will give you the list of functions.

- [ ] Could you try to verify this or whether it is an alternate cause for this error to occur?
- [ ] What ACME versions is this project compatible with/following?

> [05/15/2018 10:49:45 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Information: 0 : Add certificate for acmeConfig hostname [REDACTED FQDN]
[05/15/2018 10:49:45 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Information: 0 : RequestAndInstallInternal
[05/15/2018 10:49:46 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Information: 0 : 
[05/15/2018 10:49:46 > 8baa90: INFO] Getting AcmeServerDirectory
[05/15/2018 10:49:46 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.Read()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer)
[05/15/2018 10:49:46 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Encountered exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.Read()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__12.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<Renew>d__6.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 73
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 35
[05/15/2018 10:49:46 > 8baa90: INFO] AzureLetsEncryptRenewer.exe Error: 0 : Unexpected exception: System.AggregateException: Encountered exception(s) during cert renewal (and/or notification) ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.Read()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__12.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<Renew>d__6.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 73
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 35
[05/15/2018 10:49:46 > 8baa90: INFO]    --- End of inner exception stack trace ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 47
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.WebJobMain(String webjobName) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 53
[05/15/2018 10:49:46 > 8baa90: INFO] ---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.JsonTextReader.Read()
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[05/15/2018 10:49:46 > 8baa90: INFO]    at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer)
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__12.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:46 > 8baa90: INFO]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<Renew>d__6.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 73
[05/15/2018 10:49:46 > 8baa90: INFO] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:46 > 8baa90: INFO]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 35<---
[05/15/2018 10:49:46 > 8baa90: INFO] 
[05/15/2018 10:49:50 > 8baa90: ERR ] 
[05/15/2018 10:49:50 > 8baa90: ERR ] Unhandled Exception: System.AggregateException: Encountered exception(s) during cert renewal (and/or notification) ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.
[05/15/2018 10:49:50 > 8baa90: ERR ]    at Newtonsoft.Json.JsonTextReader.ParseValue()
[05/15/2018 10:49:50 > 8baa90: ERR ]    at Newtonsoft.Json.JsonTextReader.Read()
[05/15/2018 10:49:50 > 8baa90: ERR ]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at ACMESharp.AcmeClient.GetDirectory(Boolean saveRelative)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at LetsEncrypt.Azure.Core.Services.AcmeService.Register(RS256Signer signer)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:50 > 8baa90: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__12.MoveNext()
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:50 > 8baa90: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__13.MoveNext()
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[05/15/2018 10:49:50 > 8baa90: ERR ]    at LetsEncrypt.Azure.Core.CertificateManager.<AddCertificate>d__9.MoveNext()
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.Management.RenewalManager.<Renew>d__6.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal\Management\RenewalManager.cs:line 73
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 35
[05/15/2018 10:49:50 > 8baa90: ERR ]    --- End of inner exception stack trace ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.AppSettings.AppSettingsRenewer.<Renew>d__4.MoveNext() in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\AppSettings\AppSettingsRenewer.cs:line 47
[05/15/2018 10:49:50 > 8baa90: ERR ] --- End of stack trace from previous location where exception was thrown ---
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[05/15/2018 10:49:50 > 8baa90: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.WebJobMain(String webjobName) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 58
[05/15/2018 10:49:50 > 8baa90: ERR ]    at OhadSoft.AzureLetsEncrypt.Renewal.WebJob.Program.Main(String[] args) in C:\projects\letsencrypt-webapp-renewer\OhadSoft.AzureLetsEncrypt.Renewal\OhadSoft.AzureLetsEncrypt.Renewal.WebJob\Program.cs:line 33
[05/15/2018 10:49:50 > 8baa90: SYS INFO] Status changed to Failed
[05/15/2018 10:49:50 > 8baa90: SYS ERR ] Job failed due to exit code -532462766

**Comment by ohadschn** [comment] 2018-06-09 23:28
Hi, apologies for the late response!

I believe this is a dupe of https://github.com/sjkp/letsencrypt-siteextension/issues/211. 

I'm just calling letsencrypt-siteextension's API so whatever it supports is what I support. As such, I believe it would be best to discuss this issue there, so I'm closing this one. Perhaps you could repro this issue using `letsencrypt-siteextension` to demonstrate it's not something `letsencrypt-webapp-renewer` messes up (which I doubt, as I'm just passing on the parameters unchanged).

**Closed by ohadschn** 2018-06-09 23:28 UTC
