### ISSUE TITLE
renewXNumberOfDaysBeforeExpiration is skipping app on first run

### ISSUE THREAD

**Issue by chrfin** [ohadschn/letsencrypt-webapp-renewer#52] opened 2018-06-14 12:03 UTC
I just created a new web app and used my "65" default for `renewXNumberOfDaysBeforeExpiration` and was wondering why no certs are created, but then saw in the logs the message:

> No certificates installed issued by Let's Encrypt that are about to expire within the next 65 days. Skipping.

I think this is the wrong behavior, even if the message is correct - there is no cert expiring, but only because there is none at all -> if there is no cert I would expect it to request one and not skip it.

**Comment by ohadschn** [comment] 2018-06-14 14:09
Dupe of https://github.com/ohadschn/letsencrypt-webapp-renewer/issues/39

**Closed by ohadschn** 2018-06-14 14:09 UTC
