### ISSUE TITLE
Domain name with Cyrillic  alphabet

### ISSUE THREAD

**Issue by asapostolov** [ohadschn/letsencrypt-webapp-renewer#41] opened 2018-02-19 23:09 UTC
Hello! I have a case in which I need to configure Let's Encrypt renewer with a domain that has Cyrillic characters in the domain name. The domain name is `пм-атра.com` which is encoded in the form of `xn----8sba9bojn.com` when you do copy-paste and configure the domain in any web apps. Here's [a link](http://xn----8sba9bojn.com/) to the website(in Bulgarian).
So the problem: In Windows Azure the only way to configure this domain is with the Cyrillic name `пм-атра.com`. When I set this domain name to the WebJob configuration I get the following error when contacting the Let's Encrypt server:
![image](https://user-images.githubusercontent.com/1162471/36400404-5d92edb2-15d9-11e8-9e13-6ddb6146134a.png)
`Invalid character in DNS name`

When I set the value in WebJob's config to `xn----8sba9bojn.com`, the WebJob cannot find a configured domain with that name, because in Azure settings it's called `пм-атра.com`. I tried to remove the `пм-атра.com` name configuration from the web app domain settings and set it to `xn----8sba9bojn.com` but Azure does not let me input the domain as `xn----8sba9bojn.com`.

Is there something that can be done on the application side of the solution, so I could set `пм-атра.com` as the setting in the WebJob and maybe the app itself could translate it to `xn----8sba9bojn.com` for the request to the Let's Encrypt server but use it as `пм-атра.com` for checking and matching Windows Azure's settings?

**Comment by ohadschn** [comment] 2018-02-26 15:05
Hi @asapostolov,

I can confirm this behavior but unfortunately, my hands are tied, since I'm using a library that has this behavior. Could you open a bug for this in https://github.com/sjkp/letsencrypt-siteextension?

A better title might be "support non-ascii domain names" and mention that they should be encoded using punycode for Let's Encrypt but remain as-is for Azure operations.

**Comment by asapostolov** [comment] 2018-09-25 08:05
It seems the issue with letsencrypt-siteextension is fixed. Do you have to do anything additional or just close the issue?

**Comment by ohadschn** [comment] 2018-09-25 10:49
Don't close the issue yet, I still need to update the WebJob to use the new `letsencrypt-siteextension` library version.

**Comment by ohadschn** [comment] 2018-10-13 16:29
@asapostolov actually if you could re-open that issue ((https://github.com/sjkp/letsencrypt-siteextension/issues/199)) that would be great - I wouldn't want it to fall between the cracks...

**Comment by asapostolov** [comment] 2018-10-15 11:16
I can't for some reason. I hope they see the reference.

**Comment by ohadschn** [comment] 2018-10-15 21:36
Might be that once the owner closes a ticket, only he can re-open. I did mention Simon so he should have seen it...

**Comment by Viir** [comment] 2019-02-19 18:53
> So it looks like we're still blocked, as it was only fixed in the web extension and no [`letsencrypt.azure.core`](https://www.nuget.org/packages/letsencrypt.azure.core/) version was released with the fix. I asked Simon to release a new version...

There is now a version `0.9.3` on nuget: https://www.nuget.org/packages/letsencrypt.azure.core/0.9.3

**Comment by ohadschn** [comment] 2019-02-24 12:29
@Viir thanks for letting me know Viir, looks like there's a 0.9.5 version too - I'll take a look.

**Closed** 2019-03-16 19:48 UTC
Labels: bug

**Comment by asapostolov** [comment] 2019-04-01 08:04
@ohadschn Can you also issue a new release so people using the WebJob don't have to download and compile the project in order to the latest version?

**Comment by ohadschn** [comment] 2019-04-23 13:35
@asapostolov I'm working on a new release

**Comment by Viir** [comment] 2019-04-27 18:54
> @asapostolov I'm working on a new release

Nice! I just succesfully deployed a WebJob with version 0.9.6 here on an Azure Web App. Now I finally enabled the HTTPS support for a domain where earlier versions of the WebJob failed.

**Comment by ohadschn** [comment] 2019-04-27 21:27
@Viir glad to hear that :)
